# Base configs
url: "https://quentink-stack.github.io"
baseurl: "/photography"
# For local testing, run Jekyll with --baseurl "".
image_fulls_loc: "images/fulls"
image_thumbs_loc: "images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Quentin Kakuda"
subtitle: "Amateur Hobbyist Photographer"
author: "Quentin Kakuda"
header:
 title: "Photography"
 subtitle: "by Quentin Kakuda"
footer:
 name: "Hey there, my name is Quentin"
 bio: "I am a software enginneer and a tech aficionado, but also an automotive and motorsports enthusiast outside of work. I love photography and capturing moments, especially in the world of motorsports. "
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/queue.kei"
  medium: "https://medium.com/@quentin.k"
#   dribbble: "https://dribbble.com/rampatra"
#   linkedin: "https://in.linkedin.com/in/ram-patra"
#   github: "https://www.github.com/rampatra"
