# Base configs
baseurl: "https://quentink-stack.github.io/photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Quentin Kakuda"
subtitle: "Amateur Hobbyist Photographer"
author: "Quentin Kakuda"
header:
 title: "Photography"
 subtitle: "by Quentin Kakuda"
footer:
 name: "Hey there, my name is Quentin"
 bio: "I am a developer and a tech aficionado but an automotive and motorsports enthusiast outside of work. I love photography and capturing moments, especially in the world of motorsports. "
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
# social_urls:
#   twitter: "https://www.twitter.com/ram__patra"
#   instagram: "https://www.instagram.com/ram_patra"
#   dribbble: "https://dribbble.com/rampatra"
#   linkedin: "https://in.linkedin.com/in/ram-patra"
#   github: "https://www.github.com/rampatra"
